Anchor:
  WindowsBuildOption: &WindowsOption
    LocationPathName: Builds/windows/windows.exe
    Target: StandaloneWindows
    TargetGroup: Standalone
  PlayerSettings:
    bundleVersion: &bundleVersion "0.2"
Targets:
- Name: default
  BuildPlayerOptions:
    <<: *WindowsOption
    ExtraScriptingDefines:
    - DEFINE_A
    - DEFINE_B
    - FTBUILDER_JSON
    - FTBUILDER_YAML
- Name: "Json only"
  BuildPlayerOptions:
    <<: *WindowsOption
    ExtraScriptingDefines:
    - FTBUILDER_JSON
- Name: "Yaml Only"
  BuildPlayerOptions:
    <<: *WindowsOption
    ExtraScriptingDefines:
    - FTBUILDER_YAML
- Name: windows
  BuildPlayerOptions:
    <<: *WindowsOption
- Name: android-dev
  BuildPlayerOptions:
    LocationPathName: Builds/android/android.apk
    Target: Android
    TargetGroup: Android
    Options:
    - Development
    ExtraScriptingDefines:
    - FTBUILDER_JSON
    - FTBUILDER_YAML
  StaticProperties:
    PlayerSettings:
      bundleVersion: *bundleVersion
      keystorePass: "my-password"
      keyaliasPass: "my-password"