Anchor:
  WindowsBuildOption: &WindowsOption
    LocationPathName: Builds/windows/windows.exe
    Target: StandaloneWindows64
    TargetGroup: Standalone
    Scenes: &scenes
      - Assets/Scenes/SampleScene.unity
  PlayerSettings:
    bundleVersion: &bundleVersion "0.2"
Targets:
- Name: default
  BuildPlayerOptions:
    <<: *WindowsOption
    ExtraScriptingDefines:
    - DEFINE_A
    - DEFINE_B
    - FTBUILDER_JSON
    - FTBUILDER_YAML
- Name: "json-only"
  BuildPlayerOptions:
    <<: *WindowsOption
    ExtraScriptingDefines:
    - FTBUILDER_JSON
- Name: "yaml-only"
  BuildPlayerOptions:
    <<: *WindowsOption
    ExtraScriptingDefines:
    - FTBUILDER_YAML
- Name: windows
  BuildPlayerOptions:
    <<: *WindowsOption
    ExtraScriptingDefines:
    - DEFINE_A
    - DEFINE_B
- Name: android-dev
  BuildPlayerOptions:
    LocationPathName: Builds/android/android.apk
    Target: Android
    TargetGroup: Android
    Options:
    - Development
    Scenes: *scenes
    ExtraScriptingDefines:
    - FTBUILDER_JSON
    - FTBUILDER_YAML
  StaticProperties:
    EditorUserBuildSettings:
      buildAppBundle: false
    PlayerSettings:
      bundleVersion: *bundleVersion
      keystorePass: "my-password"
      keyaliasPass: "my-password"
- Name: android
  BuildPlayerOptions:
    LocationPathName: Builds/android/android.aab
    Target: Android
    TargetGroup: Android
    Options: []
    Scenes: *scenes
    ExtraScriptingDefines:
    - FTBUILDER_JSON
    - FTBUILDER_YAML
  StaticProperties:
    EditorUserBuildSettings:
      buildAppBundle: true
    PlayerSettings:
      bundleVersion: *bundleVersion
      keystorePass: "my-password"
      keyaliasPass: "my-password"
- Name: android-export
  BuildPlayerOptions:
    LocationPathName: Builds/android-project/
    Target: Android
    TargetGroup: Android
    Options: []
    Scenes: *scenes
    ExtraScriptingDefines:
    - FTBUILDER_JSON
    - FTBUILDER_YAML
  StaticProperties:
    EditorUserBuildSettings:
      buildAppBundle: true
      exportAsGoogleAndroidProject: true
    PlayerSettings:
      bundleVersion: *bundleVersion
      keystorePass: "my-password"
      keyaliasPass: "my-password"