Anchor:
  WindowsBuildOption: &WindowsOption
    locationPathName: Builds/windows/windows.exe
    target: StandaloneWindows
    targetGroup: Standalone
Targets:
- Name: default
  BuildPlayerOptions:
    <<: *WindowsOption
- Name: windows
  BuildPlayerOptions:
    <<: *WindowsOption
- Name: android-dev
  BuildPlayerOptions:
    locationPathName: Builds/android/android.apk
    target: Android
    targetGroup: Android
    options:
    - IL2CPP
    - Development
