name: Unity

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build my project
    runs-on: ubuntu-latest
    steps:
      # Checkout (without LFS)
      - name: Checkout repository
        uses: actions/checkout@v2

      # Git LFS
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Test
      # Test current didn't work
      # - name: Run tests
      #   uses: game-ci/unity-test-runner@v2
      #   env:
      #     UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #     UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      #     UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      #   with:
      #     githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v3
        env:
          # github ci don't support anchors
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          allowDirtyBuild: true
          buildMethod: FreeTale.Unity.Builder.Builder.BuildMain
          customParameters: --target=android-export
          versioning: Semantic

      # build android project
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.5
      - name: Run build with Gradle Wrapper
        run: ./gradlew --project-dir Builds/android-project/ build
      # - name: set up JDK 11
      #   uses: actions/setup-java@v3
      #   with:
      #     java-version: '11'
      #     distribution: 'temurin'
      #     cache: gradle
      # - run: chmod +x gradlew
      # - name: Bundle 'release' with Gradle
      #   run: ./gradlew bundleRelease
      - name: Sign AAB
        id: sign_aab
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEYSTORE }}
          alias: ${{ secrets.SIGNING_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_ALIAS_PASSWORD }}  
      - run: echo "Build status report=${{ job.status }}."
      - name: Upload App Bundle
        uses: actions/upload-artifact@v1
        with:
          name: aab
          path: ${{steps.sign_aab.outputs.signedReleaseFile}}
      # Addressable artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: Addressable
          path: ServerData
      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build